***Creating Arrays (0-D, 1-D, 2-D, 3-D, Higher Dimensions)***

- 0-D: Store a single student’s ID.

- 1-D: List of subject names or student IDs.

- 2-D: Student scores in different subjects → shape: (students, subjects).

- 3-D: Semesters or terms → shape: (terms, students, subjects)

In [15]:
import numpy as np
#2D NumPy array named scores banako
#Rows = students
#Columns = subjects (e.g., Math, Science, English)

# Example 2D: 5 students, 3 subjects
scores = np.array([
    [80, 90, 70],   # Student 1 scores in 3 subjects
    [85, 88, 75],   # Student 2
    [78, 94, 82],   # Student 3
    [92, 70, 65],   # Student 4
    [60, 76, 88],   # Student 5
])

***Access Array Elements***

Get Student 2’s Math score

In [16]:
print("Student 2 Math score:", scores[1, 0])
#ow index 1 = Student 2 (indexing starts from 0)
#Column index 0 = First subject (e.g., Math)

Student 2 Math score: 85


***Array Slicing (with Negative Slicing)***

Get last 2 students’ data

Get last subject's scores for all students

In [17]:
#-2: means start from 2nd last student and go to the end.
print(scores[-2:])         # Last 2 students
print(scores[:, -1])       # Last subject (e.g., Science)

[[92 70 65]
 [60 76 88]]
[70 75 82 65 88]


***Datatypes***

Check & convert datatypes

In [18]:

print(scores.dtype)       # Default type
scores = scores.astype('float32')  # Convert to float

int64


In [19]:
#Copy vs View
copy_scores = scores.copy()
view_scores = scores.view()
#copy() creates a completely separate array in memory.
#view() creates a new reference to the original array.

***Array Shape & Reshaping***

Shape checking and transforming into a flat array or higher dimension

In [20]:


print(scores.shape)
flat_scores = scores.reshape(-1)   # Flatten
#Reshapes the 2D array into a 1D array.
#-1 automatically calculates the correct dimension.
reshaped = scores.reshape(1, 5, 3) # 3D
#Reshapes the array into 3D: (1, 5, 3)
#1 block, 5 students, 3 subjects


(5, 3)


***Array Iteration***

Using loops or np.nditer to iterate and process data

In [21]:
for student in scores:
    print("Student Total:", np.sum(student))
#Iterates through each row (student) in scores.
#np.sum(student) adds all subject scores for that student.

# Using nditer
for x in np.nditer(scores):  #nditer() to loop through each individual value, regardless of the shape.
    print(x)


Student Total: 240.0
Student Total: 248.0
Student Total: 254.0
Student Total: 227.0
Student Total: 224.0
80.0
90.0
70.0
85.0
88.0
75.0
78.0
94.0
82.0
92.0
70.0
65.0
60.0
76.0
88.0


***Joining Arrays***

Add another semester or new student

In [22]:
new_scores = np.array([[70, 80, 90]])  # New student
scores = np.concatenate((scores, new_scores), axis=0)
#new_scores is a 2D array (1 row, 3 columns).
#np.concatenate((scores, new_scores), axis=0) joins it row-wise (adds new student to the end).

***Splitting Arrays***

Divide class into 2 groups

In [23]:
group1, group2 = np.array_split(scores, 2)
#group1, group2 will have half of the students each.

***Searching, Sorting, Filtering***

Search for students with >85 in Math

Sort by average score

Filter top performers

In [24]:

# Students with Math score > 85
math_scores = scores[:, 0] #Takes the first column (Math scores) from all rows.
high_math = np.where(math_scores > 85) #Finds the indices where Math score is greater than 85.
print("Students with high Math scores:", high_math[0]) #Displays the student indices with Math > 85.

# Sort students by total score
totals = np.sum(scores, axis=1) #Calculates total score for each student.
#axis=1 = sum across columns.
sorted_indices = np.argsort(totals)[::-1] #argsort returns indices that would sort the totals in ascending order.
#[::-1] reverses to get descending order (highest scores first).
print("Sorted student indexes:", sorted_indices) #Prints student indices in descending order of total scores.

# Filter top 3
top3 = scores[sorted_indices[:3]]
print("Top 3 Students:\n", top3)
#Selects the top 3 students based on sorted indices and prints their scores.

Students with high Math scores: [3]
Sorted student indexes: [2 1 0 5 3 4]
Top 3 Students:
 [[78. 94. 82.]
 [85. 88. 75.]
 [80. 90. 70.]]
