# Accessing/Changing specific elements, row, columns, etc

In [ ]:
import numpy as np
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) #2-d array
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a.shape #(2,7 array)

(2, 7)

In [8]:
#Get a specific elemnt [r, c]
#a[1,5]
a[1,-2]

13

In [ ]:
# Get a specific row
a[0, :]#0=first row, : = bacic slice syntsx cuz we want all elements

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
# Get a specific column
a[:, 2 ]

array([ 3, 10])

In [12]:
#Getting a little different [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
#change the array number
a[1,5]=20
print(a)

a[:,2]=[1,2] #column 2 lai 1,2 le change gareko
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
