# Create a 0-Dimensional Numpy array and check the dimensions

In [14]:
import numpy as np
n = np.array(25) #0-dimension array = single element(array with no dimension)
print(n)
print("Dimensions = ",n.ndim)
print(n.shape)
print(n.dtype)


25
Dimensions =  0
()
int32


# Create a 1-Dimensional Numpy array and check the dimensions

In [15]:
import numpy as np
n = np.array([10, 12, 30]) #1-dimension array by passing list (1 [])
print(n)
print("Dimensions = ",n.ndim)
print(n.shape)#vector so shape 3,
print(n.dtype)


[10 12 30]
Dimensions =  1
(3,)
int32


# Create a 1-Dimensional Numpy array and check the dimensions

In [16]:
import numpy as np
n = np.array([[10, 12, 30],[3,45,32]]) #2-dimension array by comparing matrix
print(n)
print("Dimensions = ",n.ndim)
print(n.shape)#in 2rows and 3 colums so
print(n.dtype)

[[10 12 30]
 [ 3 45 32]]
Dimensions =  2
(2, 3)
int32
