*no. of element in each dimension is called shape*
- why reshapr?
allows you to edit the number of elements in a dimensio also reshape() can add or remove dimensions

**Reshape dimensions from 1d to 2d**

In [9]:
import numpy as np
n = np.array([5,10,15,20,25,30])
print("1-D Array =", n)

#Reshape
resarr = n.reshape(2,3)
print("\n\nReshape Array =\n", resarr)

1-D Array = [ 5 10 15 20 25 30]


Reshape Array =
 [[ 5 10 15]
 [20 25 30]]


**Convert 3d array to 1d array (Flattening the array)**

In [8]:
n = np.array([[[5,10,15],[20,25,30]],[[35,40,45],[50,55,60]]])
print("3-D Array =",n)

#Reshape
resarr = n. reshape(-1)
print("\n\nReshaped to 1d Array =\n", resarr)


3-D Array = [[[ 5 10 15]
  [20 25 30]]

 [[35 40 45]
  [50 55 60]]]


Reshaped to 1d Array =
 [ 5 10 15 20 25 30 35 40 45 50 55 60]
