# Access Element From One-Dimensional Array

**1. Access the 1st element (index 0) from a 1D Array**

In [3]:
import numpy as np

n = np.array([10, 20, 30 ,40 ,50])
print(n)
print(n[0])

[10 20 30 40 50]
10


**2. Access the 4th element (index 3) from a 1D Array**

In [4]:
n = np.array([10, 20, 30 ,40 ,50])
print(n)
print(n[3])

[10 20 30 40 50]
40


# Access Element From Two-Dimensional Array

**1. Access the 1st element from 2D array**

In [8]:
n = np.array([[1,3,5],[2,4,6]])
print(n)
print(n[0,0])
print(n[0,1])
print(n[0,2])

[[1 3 5]
 [2 4 6]]
1
3
5


**1. Access the 2nd element from 2D array**

In [10]:
n = np.array([[1,3,5],[2,4,6]])
print(n)
print(n[1,0])
print(n[1,1])
print(n[1,2])

[[1 3 5]
 [2 4 6]]
2
4
6


# Access Element From Three-Dimensional Array

**1. Access the element from 3D array**

In [ ]:
n = np.array([[[5,6,7],[1,2,7]],[[3,7,4],[5,8,2]]]) 
print(n)
print(n[0,0,0])
print(n[0,0,1])
print(n[0,0,2])

[[[5 6 7]
  [1 2 7]]

 [[3 7 4]
  [5 8 2]]]
5
6
7


**1. Access the element from 3D array**

In [13]:
n = np.array([[[5,6,7],[1,2,7]],[[3,7,4],[5,8,2]]]) 
print(n)
print(n[1,0,0])
print(n[1,0,1])
print(n[1,0,2])

[[[5 6 7]
  [1 2 7]]

 [[3 7 4]
  [5 8 2]]]
3
7
4


# Access Elements From Last With Negative Indexing

**Access the last elemet from 1D array with negative indexing**

In [4]:
import numpy as np
n = np.array([5,2,6])
print(n)
print("\nLast element = ", n[-1])

[5 2 6]

Last element =  6


**Access the last elemet from 2D array with negative indexing**

In [7]:
n = np.array([[1,4,6],[5,3,7]])
print(n)
print("\nLast element (1st row)= ", n[0,-1])
print("\nLast element (2nd row)= ", n[1,-1])


[[1 4 6]
 [5 3 7]]

Last element (1st row)=  6

Last element (2nd row)=  7
