Slicing the array in a range from start to end is what we call Array Slicing.
- arr[start:end]
- n[1:3]
The abpve will slice two elements from index 1 to index 3 because it include the satrt index and exclude the wnd index.

# Array Slicing Example

**Slicing from index 1 to 3 (3 is excluded)**

In [1]:
import numpy as np
n = np.array([20,46,76,87,54,78,45,93,90,43])

print(n[1:3])

[46 76]


**Slicing from index 2 to 5 (5 is excluded)**

In [2]:
import numpy as np
n = np.array([20,46,76,87,54,78,45,93,90,43])

print(n[2:5])

[76 87 54]


**Slicing from index 5 to last**

In [ ]:
import numpy as np
n = np.array([20,46,76,87,54,78,45,93,90,43])

print(n[5:])
#include last as well because end range is not given

[78 45 93 90 43]


**Slicing from beginning to index 5**

In [6]:
import numpy as np
n = np.array([20,46,76,87,54,78,45,93,90,43])

print(n[:-4])

[20 46 76 87 54 78]


**Slice 1D array with STEP in Numpy**

In [11]:
n = np.array([1,4,2,5,3,6,3,7,3,6,8,9])

print(n[1:10:2])

[4 5 6 7 6]


# Slice 2D array

**Slicing from index 2 to 5(excluding5)**

In [ ]:
import numpy as np
n = np.array([[10,20,30,40,50,60],[70,80,90,97,98,99]])
print(n[0, 2:5])#from 1st row start from 2nd index to 5 but exclude 5

[30 40 50]


**Slicing for both the dimensions**

In [16]:
import numpy as np
n = np.array([[10,20,30,40,50,60],[70,80,90,97,98,99]])
print(n[0:2, 2:5])

[[30 40 50]
 [90 97 98]]
