**Check the shape of 0-D**

In [ ]:
import numpy as np
n = np.array(10)
print(n)
print(n.ndim)#no dimension
print(n.shape)#no axes, just a single value so()

10
0
()


**Check the shape of 1-D**

In [ ]:
n = np.array([1,2,6])
print(n)
print(n.ndim)
print(n.shape)
# 3 is no. of elements

[1 2 6]
1
(3,)


**Check the shape of 2-D**

In [4]:
#2x3 matrix
n = np.array([[1,3,5],[4,8,12]])
print(n)
print(n.ndim)
print(n.shape)

[[ 1  3  5]
 [ 4  8 12]]
2
(2, 3)


**Check the shape of 3-D**

In [ ]:
n = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(n)
print(n.ndim)
print(n.shape)

# 2, 3, 3
# 2 =no. of 2d array
# 2 =2d array row
# 3 =3d array column

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
