In [4]:
import numpy as np
n = np.array([1,2,3,4,5,6,7,8,9,10])

x = [True,True,False,False,False,False,False,False,False,False,]

print(n)
print(n[x])


[ 1  2  3  4  5  6  7  8  9 10]
[1 2]


**Filtered for even numbers**

In [6]:
n = np.array([1,2,3,4,5,6,7,8,9,10])

filtered = []
for a in n:
    if a %2 ==0:
        filtered.append(True)
    else:
        filtered.append(False)

print(n)
print(filtered)
print(n[filtered])


[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


**For >5**

In [7]:
n = np.array([1,2,3,4,5,6,7,8,9,10])

filtered = []
for a in n:
    if a >5:
        filtered.append(True)
    else:
        filtered.append(False)

print(n)
print(filtered)
print(n[filtered])


[ 1  2  3  4  5  6  7  8  9 10]
[False, False, False, False, False, True, True, True, True, True]
[ 6  7  8  9 10]


***Shortcut for even numbers***

In [8]:
filtered = n %2 ==0
print(n)
print(filtered)
print(n[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


***Shortcut for odd numbers***

In [10]:
filtered = n %2 ==1
print(n)
print(filtered)
print(n[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[ True False  True False  True False  True False  True False]
[1 3 5 7 9]
