# Initilize Numpy array

In [ ]:
import numpy as np
n = np.zeros([2,3])#2 rows and 3 coloum initialized with zeros 
print(n)
print(type(n))
#2 dimension array in the form of matrix 

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


*** Initilize Numpy array (Eg:2) ***

In [ ]:
import numpy as np
n = np.zeros([4,4])#4 rows and 4 coloum initialized with zeros 
print(n)
print(type(n))
#n dimension array in the form of matrix 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
