The **numpy.sort()** function is used in NumPy to sort arrays in a sequence. The sequence can be ascesnding or descending.

**Sort a One-Dimensional Integer Array**

In [2]:
import numpy as np
n = np.array([50,25,35,15,65,85,35,15,85,25])

print("Iterating array..")
for a in n:
    print(a)
#Sort
print("Sorted Array: ",np.sort(n))

Iterating array..
50
25
35
15
65
85
35
15
85
25
Sorted Array:  [15 15 25 25 35 35 50 65 85 85]


**Sort a One-Dimensional String Array**

In [3]:

n = np.array(['java','pandas','python','express','jquery'])

print("Iterating array..")
for a in n:
    print(a)
#Sort
print("Sorted Array: ",np.sort(n))

Iterating array..
java
pandas
python
express
jquery
Sorted Array:  ['express' 'java' 'jquery' 'pandas' 'python']


**Sort a Two-Dimensional Array**

In [7]:
#2x5matrix
n = np.array([[5,3,7,9,6],[15,34,67,86,78]])

print("Iterating array..")
for a in n:
    print(a)
#Sort
print("Sorted Array = \n",np.sort(n))

Iterating array..
[5 3 7 9 6]
[15 34 67 86 78]
Sorted Array = 
 [[ 3  5  6  7  9]
 [15 34 67 78 86]]
